//pages.js 감싸주는 파일 (index.js생각하면될듯)
//nav,footer같은거 넣어주면됨
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/">홈</Link>
          <Link href="list">List</Link>
          <Link href="cart">Cart</Link>
        </div>
        {children}
      </body>
    </html>
  )
}
